# Generated by Django 3.1.5 on 2021-01-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_auto_20210126_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_linked',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='insta.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insta.comment'),
        ),
    ]
