# Generated by Django 3.1.5 on 2021-01-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0010_auto_20210126_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comment',
        ),
    ]
