# Generated by Django 3.1.5 on 2021-01-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0015_auto_20210131_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_on']},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
